# Generated by Django 3.1.1 on 2022-01-07 11:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectos',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 7, 11, 22, 22, 958379, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectos',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectos',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectos',
            name='projectType',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
