# Generated by Django 3.1.1 on 2022-01-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0003_auto_20220107_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projectos',
            new_name='Projecto',
        ),
    ]
