# Generated by Django 3.1.1 on 2022-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0004_auto_20220107_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gitHub_link', models.URLField()),
                ('link', models.URLField()),
                ('projectType', models.CharField(default=False, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Projecto',
        ),
    ]
