# Generated by Django 3.1.1 on 2022-01-07 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0005_auto_20220107_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectos',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='projectos',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 7, 11, 48, 46, 139157, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
