# Generated by Django 3.1.1 on 2022-01-07 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0006_auto_20220107_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectos',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 7, 11, 50, 28, 912057, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectos',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
