# Generated by Django 3.1.1 on 2022-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0007_auto_20220107_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
