# Generated by Django 3.1.1 on 2022-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0008_auto_20220107_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='link',
            field=models.URLField(),
        ),
    ]
